### PR TITLE
Add a couple tests to TetherContent

### PR DESCRIPTION
**Pull request by ajmadsen**
A followup to my PR from last night, #97.

I added two simple tests for the operation of `TetherContent`. The second test specifically tests for what I believe to be the core of the issue of #69, the order of content rendering and tether positioning. I've tested it to fail against the prior implementation and pass against the current implementation.

I also included a fix for an issue I discovered while testing: if the `target` prop of `TetherContent` is not a function (e.g., a DOM element), an exception would be thrown as it attempted to call `target` as a function. I changed `lodash.omit` to `lodash.isfunction` as that appeared to be what should have been called.

### CODE REVIEW

**Comment by kopax** [comment]
Thanks for writing test for this, I believe you did a mistake by removing `lodash.omit` from dependencies. Could you please restore it, we can keep `lodash.isFunction`.

**Comment by ajmadsen** [comment]
My bad. I couldn’t find any other references to it so I thought I was safe. I’ll add it back in.

**Comment by ajmadsen** [comment]
Ok @kopax, I've restored `lodash.omit` to the dependencies.

**Comment by kopax** [comment]
Again thanks for this. A new [release is in progress](https://travis-ci.org/bootstrap-styled/v4/jobs/504586646)

**Pull request merged**
